[monitoring]
frequency = 1
disk_paths = ["/"]

[labels]
environment = "production"
service = "beacon-daemon-test"

[logging]
level = "debug"

[telemetry]
server = "https://beacon-web.fly.dev/api"
retry_interval = 5
interval = 10
