[labels]
environment = "production"
service = "aggregator"

[telemetry]
server = "https://beacon-web.fly.dev"
retry_interval = 5
timeout = 10

[logging]
level = "debug"

[targets]
hosts = ["192.168.149.251", "localhost"]
ports = ["80", "80"]
frequencies = [2, 1]
