[labels]
environment = "production"
service = "beacon-web"

[logging]
level = "debug"

[server]
port = 3000
shutdown_timeout = 10
allowed_origins = ["*"]
cache_ttl = 60

[database]
dsn = "test.db"

[metrics]
types = [
  "cpu_usage",
  "disk_usage",
  "uptime",
  "car_light",
  "pedestrian_light",
  "pedestrian_button",
]
units = ["percent", "bytes", "seconds", "quality"]
