[labels]
environment = "production"
service = "beacon-web"

[logging]
level = "debug"

[server]
port = 3000
shutdown_timeout = 10   # 10 seconds for when the server is shutting down
read_timeout = 5        # 5 seconds for when the server is reading
write_timeout = 10      # 10 seconds for when the server is writing
idle_timeout = 120      # 2 minutes for when the server is idle
allowed_origins = ["*"]
cache_ttl = 60

[database]
dsn = "core.db"

[metrics]
types = ["memory_used", "disk_used", "uptime", "car_light", "ped_light"]
units = ["percent", "seconds", "color"]
commands = ["notify", "reboot"]
