# fly.toml app configuration file generated for beacon-web-bold-pond-8080 on 2024-11-18T11:43:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'beacon-web'
primary_region = 'lhr'

[build]
[build.args]
GO_VERSION = '1.23.1'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
